import type { Locale } from "@/i18n";

export interface AgentNicknameRef {
  index: number;
  generation: number;
}

interface AgentNicknameEntry {
  zh: string;
  "zh-TW": string;
  en: string;
}

/** 中国历史思想家、科学家与发明家；索引只追加，不重排。 */
export const AGENT_NICKNAMES: readonly AgentNicknameEntry[] = [
  { zh: "孔子", "zh-TW": "孔子", en: "Confucius" },
  { zh: "老子", "zh-TW": "老子", en: "Laozi" },
  { zh: "墨子", "zh-TW": "墨子", en: "Mozi" },
  { zh: "孟子", "zh-TW": "孟子", en: "Mencius" },
  { zh: "庄子", "zh-TW": "莊子", en: "Zhuangzi" },
  { zh: "荀子", "zh-TW": "荀子", en: "Xunzi" },
  { zh: "韩非", "zh-TW": "韓非", en: "Han Fei" },
  { zh: "孙武", "zh-TW": "孫武", en: "Sun Wu" },
  { zh: "管仲", "zh-TW": "管仲", en: "Guan Zhong" },
  { zh: "晏婴", "zh-TW": "晏嬰", en: "Yan Ying" },
  { zh: "曾子", "zh-TW": "曾子", en: "Zengzi" },
  { zh: "子思", "zh-TW": "子思", en: "Zisi" },
  { zh: "惠施", "zh-TW": "惠施", en: "Hui Shi" },
  { zh: "公孙龙", "zh-TW": "公孫龍", en: "Gongsun Long" },
  { zh: "鬼谷子", "zh-TW": "鬼谷子", en: "Guiguzi" },
  { zh: "董仲舒", "zh-TW": "董仲舒", en: "Dong Zhongshu" },
  { zh: "王充", "zh-TW": "王充", en: "Wang Chong" },
  { zh: "郑玄", "zh-TW": "鄭玄", en: "Zheng Xuan" },
  { zh: "玄奘", "zh-TW": "玄奘", en: "Xuanzang" },
  { zh: "慧能", "zh-TW": "慧能", en: "Huineng" },
  { zh: "韩愈", "zh-TW": "韓愈", en: "Han Yu" },
  { zh: "柳宗元", "zh-TW": "柳宗元", en: "Liu Zongyuan" },
  { zh: "周敦颐", "zh-TW": "周敦頤", en: "Zhou Dunyi" },
  { zh: "张载", "zh-TW": "張載", en: "Zhang Zai" },
  { zh: "邵雍", "zh-TW": "邵雍", en: "Shao Yong" },
  { zh: "程颢", "zh-TW": "程顥", en: "Cheng Hao" },
  { zh: "程颐", "zh-TW": "程頤", en: "Cheng Yi" },
  { zh: "朱熹", "zh-TW": "朱熹", en: "Zhu Xi" },
  { zh: "陆九渊", "zh-TW": "陸九淵", en: "Lu Jiuyuan" },
  { zh: "王阳明", "zh-TW": "王陽明", en: "Wang Yangming" },
  { zh: "王夫之", "zh-TW": "王夫之", en: "Wang Fuzhi" },
  { zh: "顾炎武", "zh-TW": "顧炎武", en: "Gu Yanwu" },
  { zh: "黄宗羲", "zh-TW": "黃宗羲", en: "Huang Zongxi" },
  { zh: "颜元", "zh-TW": "顏元", en: "Yan Yuan" },
  { zh: "戴震", "zh-TW": "戴震", en: "Dai Zhen" },
  { zh: "龚自珍", "zh-TW": "龔自珍", en: "Gong Zizhen" },
  { zh: "魏源", "zh-TW": "魏源", en: "Wei Yuan" },
  { zh: "梁启超", "zh-TW": "梁啟超", en: "Liang Qichao" },
  { zh: "严复", "zh-TW": "嚴復", en: "Yan Fu" },
  { zh: "章太炎", "zh-TW": "章太炎", en: "Zhang Taiyan" },
  { zh: "王国维", "zh-TW": "王國維", en: "Wang Guowei" },
  { zh: "蔡元培", "zh-TW": "蔡元培", en: "Cai Yuanpei" },
  { zh: "胡适", "zh-TW": "胡適", en: "Hu Shi" },
  { zh: "梁漱溟", "zh-TW": "梁漱溟", en: "Liang Shuming" },
  { zh: "熊十力", "zh-TW": "熊十力", en: "Xiong Shili" },
  { zh: "冯友兰", "zh-TW": "馮友蘭", en: "Feng Youlan" },
  { zh: "金岳霖", "zh-TW": "金岳霖", en: "Jin Yuelin" },
  { zh: "钱穆", "zh-TW": "錢穆", en: "Qian Mu" },
  { zh: "鲁班", "zh-TW": "魯班", en: "Lu Ban" },
  { zh: "甘德", "zh-TW": "甘德", en: "Gan De" },
  { zh: "石申", "zh-TW": "石申", en: "Shi Shen" },
  { zh: "扁鹊", "zh-TW": "扁鵲", en: "Bian Que" },
  { zh: "李冰", "zh-TW": "李冰", en: "Li Bing" },
  { zh: "郑国", "zh-TW": "鄭國", en: "Zheng Guo" },
  { zh: "张仲景", "zh-TW": "張仲景", en: "Zhang Zhongjing" },
  { zh: "华佗", "zh-TW": "華佗", en: "Hua Tuo" },
  { zh: "蔡伦", "zh-TW": "蔡倫", en: "Cai Lun" },
  { zh: "杜诗", "zh-TW": "杜詩", en: "Du Shi" },
  { zh: "张衡", "zh-TW": "張衡", en: "Zhang Heng" },
  { zh: "马钧", "zh-TW": "馬鈞", en: "Ma Jun" },
  { zh: "王叔和", "zh-TW": "王叔和", en: "Wang Shuhe" },
  { zh: "皇甫谧", "zh-TW": "皇甫謐", en: "Huangfu Mi" },
  { zh: "刘徽", "zh-TW": "劉徽", en: "Liu Hui" },
  { zh: "葛洪", "zh-TW": "葛洪", en: "Ge Hong" },
  { zh: "陶弘景", "zh-TW": "陶弘景", en: "Tao Hongjing" },
  { zh: "祖冲之", "zh-TW": "祖沖之", en: "Zu Chongzhi" },
  { zh: "贾思勰", "zh-TW": "賈思勰", en: "Jia Sixie" },
  { zh: "郦道元", "zh-TW": "酈道元", en: "Li Daoyuan" },
  { zh: "綦毋怀文", "zh-TW": "綦毋懷文", en: "Qimu Huaiwen" },
  { zh: "巢元方", "zh-TW": "巢元方", en: "Chao Yuanfang" },
  { zh: "孙思邈", "zh-TW": "孫思邈", en: "Sun Simiao" },
  { zh: "李淳风", "zh-TW": "李淳風", en: "Li Chunfeng" },
  { zh: "一行", "zh-TW": "一行", en: "Yixing" },
  { zh: "陆羽", "zh-TW": "陸羽", en: "Lu Yu" },
  { zh: "李皋", "zh-TW": "李皋", en: "Li Gao" },
  { zh: "毕昇", "zh-TW": "畢昇", en: "Bi Sheng" },
  { zh: "喻皓", "zh-TW": "喻皓", en: "Yu Hao" },
  { zh: "沈括", "zh-TW": "沈括", en: "Shen Kuo" },
  { zh: "苏颂", "zh-TW": "蘇頌", en: "Su Song" },
  { zh: "秦九韶", "zh-TW": "秦九韶", en: "Qin Jiushao" },
  { zh: "李冶", "zh-TW": "李冶", en: "Li Ye" },
  { zh: "杨辉", "zh-TW": "楊輝", en: "Yang Hui" },
  { zh: "郭守敬", "zh-TW": "郭守敬", en: "Guo Shoujing" },
  { zh: "王恂", "zh-TW": "王恂", en: "Wang Xun" },
  { zh: "赵友钦", "zh-TW": "趙友欽", en: "Zhao Youqin" },
  { zh: "王祯", "zh-TW": "王禎", en: "Wang Zhen" },
  { zh: "朱世杰", "zh-TW": "朱世傑", en: "Zhu Shijie" },
  { zh: "黄道婆", "zh-TW": "黃道婆", en: "Huang Daopo" },
  { zh: "李时珍", "zh-TW": "李時珍", en: "Li Shizhen" },
  { zh: "徐光启", "zh-TW": "徐光啟", en: "Xu Guangqi" },
  { zh: "徐霞客", "zh-TW": "徐霞客", en: "Xu Xiake" },
  { zh: "宋应星", "zh-TW": "宋應星", en: "Song Yingxing" },
  { zh: "宋慈", "zh-TW": "宋慈", en: "Song Ci" },
  { zh: "王惟一", "zh-TW": "王惟一", en: "Wang Weiyi" },
  { zh: "滑寿", "zh-TW": "滑壽", en: "Hua Shou" },
  { zh: "朱丹溪", "zh-TW": "朱丹溪", en: "Zhu Danxi" },
  { zh: "杨继洲", "zh-TW": "楊繼洲", en: "Yang Jizhou" },
  { zh: "李诫", "zh-TW": "李誡", en: "Li Jie" },
  { zh: "丁缓", "zh-TW": "丁緩", en: "Ding Huan" },
  { zh: "蒲元", "zh-TW": "蒲元", en: "Pu Yuan" },
  { zh: "黄履庄", "zh-TW": "黃履莊", en: "Huang Lüzhuang" },
  { zh: "戴梓", "zh-TW": "戴梓", en: "Dai Zi" },
  { zh: "梅文鼎", "zh-TW": "梅文鼎", en: "Mei Wending" },
  { zh: "明安图", "zh-TW": "明安圖", en: "Ming Antu" },
  { zh: "汪莱", "zh-TW": "汪萊", en: "Wang Lai" },
  { zh: "李锐", "zh-TW": "李銳", en: "Li Rui" },
  { zh: "董祐诚", "zh-TW": "董祐誠", en: "Dong Youcheng" },
  { zh: "罗士琳", "zh-TW": "羅士琳", en: "Luo Shilin" },
  { zh: "邹伯奇", "zh-TW": "鄒伯奇", en: "Zou Boqi" },
  { zh: "李善兰", "zh-TW": "李善蘭", en: "Li Shanlan" },
  { zh: "华蘅芳", "zh-TW": "華蘅芳", en: "Hua Hengfang" },
  { zh: "徐寿", "zh-TW": "徐壽", en: "Xu Shou" },
  { zh: "詹天佑", "zh-TW": "詹天佑", en: "Zhan Tianyou" },
  { zh: "冯如", "zh-TW": "馮如", en: "Feng Ru" },
  { zh: "侯德榜", "zh-TW": "侯德榜", en: "Hou Debang" },
  { zh: "茅以升", "zh-TW": "茅以升", en: "Mao Yisheng" },
  { zh: "竺可桢", "zh-TW": "竺可楨", en: "Zhu Kezhen" },
  { zh: "李四光", "zh-TW": "李四光", en: "Li Siguang" },
  { zh: "丁文江", "zh-TW": "丁文江", en: "Ding Wenjiang" },
  { zh: "翁文灏", "zh-TW": "翁文灝", en: "Weng Wenhao" },
  { zh: "叶企孙", "zh-TW": "葉企孫", en: "Ye Qisun" },
  { zh: "吴有训", "zh-TW": "吳有訓", en: "Wu Youxun" },
  { zh: "严济慈", "zh-TW": "嚴濟慈", en: "Yan Jici" },
  { zh: "赵忠尧", "zh-TW": "趙忠堯", en: "Zhao Zhongyao" },
  { zh: "钱学森", "zh-TW": "錢學森", en: "Qian Xuesen" },
  { zh: "华罗庚", "zh-TW": "華羅庚", en: "Hua Luogeng" },
  { zh: "苏步青", "zh-TW": "蘇步青", en: "Su Buqing" },
  { zh: "陈省身", "zh-TW": "陳省身", en: "Shiing-Shen Chern" },
] as const;

export function agentNicknameLabel(
  nickname: AgentNicknameRef,
  locale: Locale,
): string {
  const entry = AGENT_NICKNAMES[nickname.index];
  const base = entry?.[locale] ?? `Agent ${nickname.index + 1}`;
  return nickname.generation > 1 ? `${base} #${nickname.generation}` : base;
}

export function agentNicknameSeed(nickname: AgentNicknameRef): string {
  return `keencode-agent-nickname:${nickname.index}:${nickname.generation}`;
}
